### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by floriancargoet** [Spicesoft/tandoori_rn#1]
- [ ] Gérer la traduction côté RN
- [ ] Unifier la traduction RN/Android/iOS
- [ ] [iOS] Différencier Debug = Dev, Release = Prod (4 configs + script xcode-build.sh custom)
- [ ] [iOS] Dé-dupliquer les variables de config entre les 4 configs 
- [ ] Maintenir ou PR react-native-eval
- [ ] [iOS] [Bug RCTAnimation](https://github.com/facebook/react-native/issues/13198)
